---
version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: bridge
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "dockerhost:${DOCKERHOST}"
    expose:
      - "32181"
      - "2000"
    ports:
      - "32181:32181"
      - "2000:2000"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: bridge
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${DOCKERHOST}:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKERHOST}:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "dockerhost:${DOCKERHOST}"
    expose:
      - "29092"
    ports:
      - "29092:29092"
